### ISSUE TITLE
regex matches

### ISSUE THREAD

**Issue by slaterslater** [danishalim/URLChecker#6]
I ran your tool against the source of [Planet CDOT Feed List](https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List)
The regex doesn't match <http://en.wikipedia.org/wiki/RSS_(file_format)>
It's parsed as <http://en.wikipedia.org/wiki/RSS_>
```code
[SUCCESS] Status: [200] http://en.wikipedia.org/wiki/RSS_
```
You can see the full list of valid URL characters here: <https://developers.google.com/maps/documentation/urls/url-encoding>

**Comment by danishalim** [comment]
Changed regex. Thanks.
